project:
  type: website
  output-dir: _book

website:
  title: "微生物群落协同生长驱动多稳态论文复现"
  navbar:
    left:
      - href: index.qmd
        text: 首页

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: false
    number-sections: true

render:
  - index.qmd
